import { cleanText, normalizeEmail, sha256 } from './http.js';

const AGREEMENT_VERSION = '2.3';
const EFFECTIVE_DATE = 'July 26, 2026';

const esc = (value) => String(value ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#039;');
const money = (cents) => cents == null ? 'To be confirmed' : (Number(cents) / 100).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const dateTime = (epoch) => new Intl.DateTimeFormat('en-US', { timeZone: 'America/Los_Angeles', dateStyle: 'long', timeStyle: 'short' }).format(new Date(Number(epoch) * 1000));
const p = (text) => `<p>${text}</p>`;
const ul = (items) => `<ul>${items.map((item) => `<li>${item}</li>`).join('')}</ul>`;
const section = (title, body, className = '') => `<section class="agreement-section ${className}"><h2>${title}</h2>${body}</section>`;
const addendum = (id, title, body) => `<section class="agreement-addendum" data-agreement-module="${id}"><p class="addendum-label">Booking-specific equipment terms</p><h2>${title}</h2>${body}</section>`;

export function determineAgreementModules(items = []) {
  const found = new Set();
  for (const item of items) {
    const text = [item.category, item.style, item.name, item.sku, item.description].join(' ').toLowerCase();
    if (/tables? & chairs|table|chair|stanchion|red carpet|backdrop|decor|furnish/.test(text)) found.add('furnishings');
    if (/tents? & shade|canopy|pop[ -]?up|tent/.test(text)) found.add('canopy');
    if (/backyard games?|mini golf|mini-golf|cornhole|jenga|connect four|ring toss|yard game|tug.of.war|game/.test(text)) found.add('games');
    if (/photo booths? & guestbooks|photo booth|photo-booth|audio guestbook|video guestbook|guestbook|camera|printer|props?/.test(text)) found.add('photo');
    if (/audio & visual|projector|screen|display|television|\btv\b|pa system|speaker|microphone|karaoke|lighting|uplight|audio|visual|fan|mister|electrical/.test(text)) found.add('av');
    if (/starlink|wi-?fi|wifi|internet|network|connectivity|router|cellular|hotspot/.test(text)) found.add('connectivity');
  }
  return [...found];
}

const moduleTitles = {
  furnishings: 'Tables, Chairs, Event Furnishings & Decor',
  canopy: '10 × 10 Pop-Up Canopies',
  games: 'Portable Mini Golf & Non-Powered Backyard Games',
  photo: 'Photo Booths, Audio Guestbooks & Recording Equipment',
  av: 'Projectors, Audio, Lighting, Fans, Misters & Electrical Equipment',
  connectivity: 'Event Internet & Network-Connectivity Equipment'
};

function summary(booking, items, paymentMethod, depositCents) {
  const security = paymentMethod === 'card_on_file'
    ? 'Card on file — designated by Regal Rentals'
    : paymentMethod === 'security_deposit'
      ? `Security deposit — designated by Regal Rentals${depositCents == null ? '' : ` (${money(depositCents)})`}`
      : 'Regal Rentals will designate card on file or security deposit before equipment release';
  const location = [booking.event_address, booking.event_city].filter(Boolean).join(', ') || 'To be confirmed';
  return `<section class="booking-summary"><h2>Booking Summary</h2><dl class="booking-facts">
    <div><dt>Booking</dt><dd>${esc(booking.booking_number)}</dd></div><div><dt>Agreement</dt><dd>Version ${AGREEMENT_VERSION}</dd></div>
    <div><dt>Customer</dt><dd>${esc(booking.customer_name)}</dd></div><div><dt>Email</dt><dd>${esc(booking.customer_email)}</dd></div>
    <div><dt>Phone</dt><dd>${esc(booking.customer_phone)}</dd></div><div><dt>Service</dt><dd>${booking.service_type === 'pickup' ? 'Customer pickup' : 'Delivery'}</dd></div>
    <div><dt>Event window</dt><dd>${esc(dateTime(booking.event_start_at))} through ${esc(dateTime(booking.event_end_at))}</dd></div>
    <div><dt>Location</dt><dd>${esc(location)}</dd></div><div><dt>Known subtotal</dt><dd>${esc(money(booking.subtotal_cents))}</dd></div>
    <div><dt>Payment security</dt><dd>${esc(security)}</dd></div><div><dt>Balance due</dt><dd>Before release unless the confirmed quote says otherwise</dd></div>
  </dl><h3>Rental items</h3><ul class="booking-items">${items.map((item) => `<li><strong>${esc(item.quantity)} × ${esc(item.name)}</strong><span>${item.unit_price_cents == null ? 'Price to be confirmed' : `${esc(money(item.unit_price_cents))} each`}</span></li>`).join('')}</ul></section>`;
}

function core(booking, modules, paymentMethod) {
  const payment = paymentMethod === 'card_on_file'
    ? 'Regal Rentals has designated CARD ON FILE for this booking.'
    : paymentMethod === 'security_deposit'
      ? 'Regal Rentals has designated SECURITY DEPOSIT for this booking.'
      : 'Regal Rentals will designate either CARD ON FILE or SECURITY DEPOSIT before equipment release. This is selected by Regal Rentals, not the customer.';
  return `<div class="included-modules"><strong>Booking-specific sections included:</strong>${modules.map((id) => `<span>${esc(moduleTitles[id])}</span>`).join('')}</div>
  ${section('1. Agreement and Acceptance', p('This Agreement is between UMBRYL LLC, a California limited liability company doing business as Regal Rentals ("Regal Rentals") and the customer identified in the Booking Summary ("Customer"). It includes the Booking Summary, item list, pricing, Schedule A, only the booking-specific equipment sections generated below, written instructions provided before use, approved written changes, and condition records.') + p('Customer accepts this Agreement only by affirmatively signing it. The signer represents that the signer is at least 18 years old, that the booking information is accurate, and that the signer has authority to bind Customer and any organization named in the Booking Summary. A signer does not automatically release claims belonging to unrelated guests, minors, venues, or other third parties.'))}
  ${section('2. Covered Equipment and Excluded Activities', p('This Agreement applies only to equipment and services specifically listed in the Booking Summary. The generated document intentionally omits equipment sections that do not apply to this booking.') + p('Unless the exact activity is approved in a separate signed addendum, this Agreement does not authorize bounce houses or other inflatables; amusement rides; powered attractions; dunk tanks or water attractions; watercraft; climbing equipment; elevated participant platforms; axe, knife, weapon, or projectile throwing; generators; lasers; pyrotechnics; smoke, haze, or flame effects; cooking equipment; heaters; or any activity prohibited by law, venue rules, manufacturer instructions, or insurance.'))}
  ${section('3. Rental Period; Custody; Return', p('Customer responsibility begins when equipment is delivered, made available for pickup, or otherwise placed under Customer control and continues until Regal Rentals physically receives, inspects, and accepts it as returned. Equipment that is inaccessible, unattended, wet, dirty, disassembled, mixed with third-party property, or otherwise not ready remains in Customer custody and may result in additional rental, labor, travel, cleaning, or retrieval charges.'))}
  ${section('4. Charges, Payment, Cancellation, and Rescheduling', p(`Customer shall pay all charges, taxes, reservation payments, balances, and other amounts disclosed before signing or in an approved written change. ${payment} A security deposit is security only, is not a damage waiver, and does not limit Customer responsibility.`) + p('If CARD ON FILE is designated, Customer authorizes scheduled charges and documented additional charges permitted by this Agreement and Schedule A. If SECURITY DEPOSIT is designated, Regal Rentals may apply it to documented amounts due and invoice any remaining balance. Before a nonscheduled card charge or deposit deduction, Regal Rentals will send an itemized notice with supporting records when reasonably available and normally allow at least 48 hours for a good-faith written dispute.') + p('Because reserved inventory is removed from availability and may cause declined bookings or committed labor and costs, actual cancellation losses may be impracticable or extremely difficult to determine when the booking is made. These amounts are intended as reasonable estimates, not penalties:') + ul(['At least 14 full calendar days before the rental: refund amounts paid, less disclosed nonrefundable third-party and payment-processing costs.', '7 through 13 full calendar days before the rental: Customer owes 50% of the booking price.', 'Fewer than 7 full calendar days before the rental, after dispatch, or after pickup: Customer owes 100% of the booking price.', 'One reschedule may be requested with at least 7 full calendar days notice, within 180 days and subject to availability.']) + p('Weather concerns do not automatically cancel a booking. If Regal Rentals receives net revenue from rebooking substantially the same inventory and time, it will apply a reasonable credit to avoid duplicate recovery. If a stated cancellation amount is unenforceable, Regal Rentals may recover only actual damages and documented nonrecoverable costs to the extent permitted by law.'))}
  ${section('5. Delivery, Pickup, Site Access, and Cooperation', p('Customer shall provide accurate directions, safe and unobstructed access, adequate loading space, a responsible adult contact, and required gate codes, elevators, parking, permits, venue approvals, and utility access. Customer shall identify underground utilities, irrigation, septic systems, overhead lines, unstable soil, slopes, buried hazards, and venue restrictions before setup. Regal Rentals may refuse unsafe, illegal, inaccessible, or damaging delivery or setup conditions.') + (booking.service_type === 'pickup' ? p('For customer pickup, Customer is responsible for a suitable vehicle, proper loading, secure tie-downs, lawful transport, weather protection, and timely return. Regal Rentals may refuse loading when the vehicle or load plan appears unsafe or inadequate.') : ''))}
  ${section('6. Inspection, Instructions, and Unsafe Conditions', p('Customer shall promptly inspect equipment and report visible shortages, defects, contamination, instability, or damage before use and no later than 30 minutes after custody begins. This does not waive a latent defect that could not reasonably have been discovered. Customer shall immediately stop use, isolate equipment, protect others, and contact Regal Rentals if equipment or conditions appear unsafe. Customer shall review and communicate all labels and written instructions and follow the strictest applicable safety requirement.'))}
  ${section('7. Care, Security, Supervision, and Prohibited Conduct', p('Customer has care, custody, and control during the rental and shall protect equipment from theft, vandalism, misuse, weather, animals, vehicles, sprinklers, fire, smoke, food, beverages, mud, sand, saltwater, and unauthorized relocation or alteration.') + ul(['Do not subrent, lend, sell, conceal, modify, drill, cut, paint, tape, glue, staple, overload, or repair equipment without written permission.', 'Do not move installed equipment unless written instructions permit it.', 'Do not allow intoxicated, reckless, unsupervised, untrained, or physically incapable persons to set up, move, operate, climb on, or misuse equipment.', 'Keep equipment away from flames, fireworks, smoking materials, cooking devices, pools, roads, stairs, drop-offs, and other hazards.', 'Follow all labels, manufacturer instructions, weight limits, venue rules, permits, laws, and Regal Rentals directions.']) + p('Customer is responsible for employees, contractors, family members, guests, invitees, attendees, vendors, and all users. Children must be directly supervised. Rental equipment is not childcare.'))}
  ${section('8. Weather and Emergency Shutdown', p('Customer accepts responsibility for monitoring weather and site conditions. Wind, gusts, rain, lightning, heat, cold, smoke, flooding, unstable soil, and other conditions can make equipment unsafe even if setup was initially proper. Customer shall immediately stop use, evacuate persons, disconnect power when safe, and follow Regal Rentals instructions whenever conditions appear unsafe. Regal Rentals may order shutdown, evacuation, or retrieval, and use may not resume until authorized.'))}
  ${section('9. Loss, Theft, Damage, Cleaning, and Replacement', p('Customer is responsible for loss, theft, disappearance, destruction, contamination, misuse, unauthorized repair, and damage beyond ordinary wear during Customer custody, except to the extent finally determined to have resulted from Regal Rentals nonwaivable misconduct. Customer shall pay reasonable documented inspection, cleaning, sanitizing, drying, repair, restoration, retrieval, or replacement costs, less reasonable salvage value or later usable recovery. Ordinary wear does not include stains, burns, tears, cracks, bent frames, broken mechanisms, water damage, mold, smoke or odor contamination, missing parts, excessive dirt, tape, glue, paint, glitter, food, bodily fluids, pet damage, or improper weather exposure.'))}
  ${section('10. Assumption of Risk — Read Carefully', p('<strong>CUSTOMER UNDERSTANDS THAT DELIVERY, SETUP, POSSESSION, MOVEMENT, TRANSPORT, PLACEMENT, AND USE OF RENTAL EQUIPMENT INVOLVE KNOWN AND UNKNOWN RISKS OF PROPERTY DAMAGE, PERSONAL INJURY, ILLNESS, DISABILITY, AND DEATH. RISKS MAY INCLUDE FALLS; TRIPS; PINCHING OR CRUSHING; COLLAPSE OR TIPPING; IMPACT FROM PUTTERS, BALLS, GAME PIECES, STANDS OR FALLING OBJECTS; ELECTRIC SHOCK; CABLE, SOUND, LIGHT, WIND, LIGHTNING, FIRE, WATER, EQUIPMENT, ANCHOR, GROUND, MISUSE, SUPERVISION, AND THIRD-PARTY RISKS; AND RISKS CAUSED IN WHOLE OR IN PART BY THE ORDINARY NEGLIGENCE OF A RELEASED PARTY. TO THE FULLEST EXTENT PERMITTED BY LAW, CUSTOMER KNOWINGLY AND VOLUNTARILY ACCEPTS AND ASSUMES ALL SUCH RISKS REASONABLY RELATED TO THE RENTAL.</strong>'), 'legal-callout')}
  ${section('11. Release of Liability for Ordinary Negligence — Read Carefully', p('<strong>TO THE FULLEST EXTENT PERMITTED BY CALIFORNIA LAW, CUSTOMER, FOR CUSTOMER AND CUSTOMER\'S HEIRS, ESTATE, PERSONAL REPRESENTATIVES, SUCCESSORS, AND ASSIGNS, RELEASES, WAIVES, AND FOREVER DISCHARGES UMBRYL LLC DBA REGAL RENTALS AND ITS MEMBERS, MANAGERS, OWNERS, OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, DELIVERY AND SETUP PERSONNEL, SUCCESSORS, AND ASSIGNS (THE "RELEASED PARTIES") FROM CUSTOMER\'S OWN CLAIMS FOR PERSONAL INJURY, DEATH, OR PROPERTY DAMAGE ARISING OUT OF OR REASONABLY RELATED TO THE RENTAL, INCLUDING CLAIMS CAUSED IN WHOLE OR IN PART BY THE ORDINARY NEGLIGENCE OF A RELEASED PARTY. THIS RELEASE APPLIES TO ORDINARY NEGLIGENT INSPECTION, MAINTENANCE, INSTRUCTION, DELIVERY, SETUP, PLACEMENT, WARNING, OR RETRIEVAL. IT DOES NOT APPLY TO GROSS NEGLIGENCE, RECKLESS OR WILLFUL MISCONDUCT, FRAUD, INTENTIONAL INJURY, VIOLATION OF LAW, OR LIABILITY THAT CANNOT LAWFULLY BE RELEASED.</strong>'), 'legal-callout')}
  ${section('12. Covenant Not to Sue; Third-Party Claims; Indemnity', p('Customer agrees not to maintain a claim released under Section 11, while retaining the right to report an incident or assert any nonwaivable claim. To the fullest extent permitted by law, Customer shall indemnify and hold harmless the Released Parties from third-party claims, damages, judgments, fines, penalties, losses, and reasonable attorneys fees and costs to the extent arising from Customer breach; acts or omissions of Customer or Customer users; Customer site, supervision, security, power, permits, or instructions; damage during Customer custody; or unauthorized or unsafe use, movement, alteration, transport, or operation. Customer is not required to assume control of a legal defense before responsibility is determined, and this obligation does not apply to the extent caused by nonwaivable misconduct of a Released Party.'))}
  ${section('13. Limitation of Contractual Liability; No Event Guarantee', p('To the fullest extent permitted by law, Regal Rentals is not liable for lost profits, revenue, opportunity, goodwill, data, event enjoyment, substitute rentals, venue charges, or other indirect, incidental, special, exemplary, punitive, or consequential damages arising from delay, cancellation, interruption, unavailability, or performance. For contractual claims not involving personal injury, death, fraud, willful misconduct, violation of law, or other nonwaivable liability, aggregate liability will not exceed rental charges actually paid for the specific equipment or service giving rise to the claim. Regal Rentals provides serviceable equipment for ordinary intended use but does not guarantee uninterrupted use, an event outcome, guest participation, media delivery, compatibility, internet availability, sound or image quality, or protection from weather.'))}
  ${section('14. Insurance; Incident Reporting; Records', p('Customer is responsible for insurance appropriate to the event, site, equipment, and activities. Regal Rentals may require proof of insurance or additional-insured status. Insurance coverage is governed solely by applicable policies and is not expanded by this Agreement. Customer shall immediately report injury, property damage, theft, malfunction, emergency response, insurance claims, or threatened claims and, when safe, preserve the scene and equipment, identify witnesses, take photographs, and cooperate with reasonable investigation.') + p('The parties agree to transact electronically. Typing a name, checking consent, drawing or adopting an electronic signature, and selecting Agree and Sign constitute a binding signature. Regal Rentals may retain the exact agreement version, booking information, communications, payment records, photographs, signature, timestamp, Internet Protocol address, browser information, and related audit data to perform and document the transaction, prevent fraud, collect amounts due, investigate incidents, enforce this Agreement, and comply with law.'))}
  ${section('15. Default; Governing Law; Entire Agreement', p('If Customer fails to pay, return equipment, provide access, or comply, Regal Rentals may suspend performance, retrieve equipment where lawfully permitted, apply deposits, charge authorized amounts, use collection services, report suspected theft or conversion, and pursue lawful remedies. The prevailing party may recover reasonable attorneys fees and costs to the extent permitted by law. California law governs. Subject to nonwaivable venue rules, proceedings shall be brought in El Dorado County, California. Provisions are severable and may be narrowly reformed when permitted.') + p('This Agreement, Booking Summary, item list, Schedule A, generated equipment terms, instructions identified before signing, and approved changes are the complete agreement. Written equipment addenda control over the Booking Summary; the Booking Summary controls over Schedule A; Schedule A controls only as to disclosed rates and calculations. Changes must be written or electronic. Payment, damage, release, indemnity, limitations, records, and remedies survive.'))}`;
}

function addenda(modules) {
  const out = [];
  if (modules.includes('furnishings')) out.push(addendum('furnishings', moduleTitles.furnishings, p('Use furnishings only on stable, level surfaces and for intended purposes. Do not stand, climb, jump, lean back, rock, drag occupied furniture, use tables as platforms, sit on stanchions, pull on ropes, or permit uneven loading. Keep fingers and children clear of folding mechanisms. Keep aisles, exits, accessible routes, carpet edges, cords, bases, and stands safe. Outdoor backdrops, signs, and decor must be secured and removed from use if unstable.')));
  if (modules.includes('canopy')) out.push(addendum('canopy', moduleTitles.canopy, p('A canopy is a temporary shade structure, not a storm or emergency shelter. Only Regal Rentals or a person authorized in writing may install, relocate, adjust, anchor, add sidewalls, or dismantle it.') + ul(['Every leg must remain secured using the anchoring or weighting method selected by Regal Rentals. Do not remove, loosen, shift, cover, or obstruct anchoring.', 'Keep exits, walkways, anchor points, and guy lines visible and unobstructed. Prevent climbing, hanging, swinging, or pulling on the frame, fabric, weights, ropes, or stakes.', 'No cooking, grilling, open flame, fireworks, smoking materials, heater, or heat-producing device is permitted under or dangerously close to the canopy unless the exact use is approved in writing.', 'No sidewall, banner, sign, lighting, decoration, speaker, cable, tarp, or attachment may be added without approval.']) + p('Customer is responsible for site and venue approval and permit and fire-code requirements unless the Booking Summary says otherwise. The lowest manufacturer, venue, government, or Regal Rentals shutdown limit controls. Immediately evacuate and stop use if the canopy moves, lifts, leans, pools water, tears, loosens, makes unusual noise, loses an anchor, a weather warning is issued, or conditions otherwise appear unsafe.')));
  if (modules.includes('games')) out.push(addendum('games', moduleTitles.games, p('Provide a clear, level, adequately lighted play area separated from roads, vehicle paths, stairs, pools, drop-offs, windows, fragile property, electrical cables, and unrelated traffic. Keep equipment in the approved layout.') + ul(['Putters are for controlled putting strokes only. No full or overhead swings, swordplay, throwing, or swinging while another person is within reach.', 'Do not stand, sit, climb, jump, or ride on mini-golf units, obstacles, ramps, game boards, blocks, or containers.', 'Do not throw components except in the ordinary manner required by a tossing game, and never aim at people, animals, windows, vehicles, or fragile property.', 'Children must be actively supervised. Control lines, crowding, and horseplay.', 'Immediately stop use if turf, edging, fasteners, legs, joints, obstacles, game pieces, or any unit shifts, breaks, splinters, exposes hardware, becomes wet or slippery, or appears unsafe.', 'Collect loose balls, blocks, and game pieces when play stops.']) + p('Custom-built equipment is only for its stated recreational purpose and may not be modified, disassembled, elevated, combined, or used for an unintended challenge.')));
  if (modules.includes('photo')) out.push(addendum('photo', moduleTitles.photo, p('Recording use must be voluntary, visible, and supervised. Customer is responsible for event notices and permissions for photos, videos, audio messages, confidential communications, and minors. Hidden, deceptive, or nonconsensual recording is prohibited.') + ul(['Only users who intentionally activate equipment may be recorded.', 'Prevent unauthorized access to recordings, settings, memory cards, accounts, and download links.', 'Keep backdrops, stands, printers, screens, and props stable and clear of exits; do not climb, hang from, lean on, relocate, or attach unapproved items.', 'Keep food, drinks, confetti, glitter, smoke, moisture, and loose decorations away from electronics.', 'Customer is responsible for guest conduct and improper content.']) + p('Digital delivery, QR codes, texts, email, uploads, galleries, printing, and storage may depend on power, internet, third-party platforms, and compatible customer information. Uninterrupted delivery, permanent storage, and recovery are not guaranteed. Unless otherwise stated, Customer shall download desired media within 30 days after the later of rental end or initial delivery.')));
  if (modules.includes('av')) out.push(addendum('av', moduleTitles.av, p('Electrical equipment must remain dry, ventilated, stable, and protected from impact, heat, sprinklers, rain, condensation, beverages, and unauthorized access. Use only approved voltage, outlets, cords, power distribution, adapters, and protective devices.') + ul(['Do not overload circuits, bypass breakers or ground pins, use damaged cords, create prohibited daisy chains, open enclosures, alter wiring, settings, or perform repairs.', 'Customer is responsible for safe cable routing unless Regal Rentals provides it. Do not cross exits, stairs, roads, or walkways without suitable protection.', 'Do not cover, move, or disconnect a projector while operating or before cooling completes, and do not direct its beam into eyes.', 'Keep screens, televisions, speakers, microphones, tripods, and lighting stands secured. Do not climb, hang from, lean on, relocate, or add unapproved loads.', 'Keep sound levels lawful and reasonable. Avoid strobe effects around photosensitive persons or where prohibited.', 'Keep fan and mister electrical connections dry, prevent pooling, and stop use for leaks or instability.']) + p('Customer devices, media, accounts, cables, adapters, Wi-Fi, and venue power may be incompatible or unreliable. Compatibility and continuous operation are not guaranteed unless Regal Rentals tested and provides the complete signal and power path.')));
  if (modules.includes('connectivity')) out.push(addendum('connectivity', moduleTitles.connectivity, p('Connectivity may depend on satellite or cellular coverage, line of sight, congestion, weather, third-party networks, power, and service-provider rules. Coverage, speed, latency, uninterrupted service, and suitability for critical use are not guaranteed.') + ul(['Use the network lawfully; no infringement, harassment, unauthorized access, interception, malware distribution, excessive automated traffic, or prohibited activity.', 'Customer is responsible for the security and privacy of connected devices and information.', 'Do not move antennas, obstruct sky view or ventilation, reset equipment, change passwords or settings, connect unapproved switches or high-load devices, or expose equipment to weather unless instructed.'])));
  return out.join('');
}

function scheduleAndAcknowledgments(modules) {
  const rows = [
    ['Late return', 'The disclosed rate applies. If none is disclosed, the ordinary daily rental rate applies for each started 24-hour period plus reasonable documented labor or travel caused by delay.'],
    ['Waiting / inaccessible site', 'Only a disclosed rate applies; otherwise only reasonable documented third-party or out-of-pocket costs caused by Customer may be charged.'],
    ['Cleaning / contamination', 'Reasonable documented labor, materials, and third-party costs beyond ordinary turnover.'],
    ['Repair / replacement / missing items', 'Reasonable documented inspection, repair, parts, freight, assembly, configuration, or substantially similar replacement costs, with reasonable credits for salvage or later usable return.'],
    ['Redelivery / retrieval / site revisit', 'A disclosed amount or reasonable documented travel, labor, parking, toll, and third-party costs caused by Customer.'],
    ['Consumables / prints / media', 'Only quantities and overage rates disclosed before signing apply.'],
    ['Returned payments / collection', 'Actual fees and reasonable collection costs permitted by law and caused by a failed or wrongfully disputed payment.'],
    ['Damage waiver', 'None is included unless separately described, priced, and accepted. A deposit or card authorization is payment security, not a damage waiver.']
  ];
  return `<section class="agreement-schedule"><h2>Schedule A — Standard Additional Charge Rules</h2><div class="charge-list">${rows.map(([name, rule]) => `<div><h3>${esc(name)}</h3><p>${esc(rule)}</p></div>`).join('')}</div></section>
  <section class="agreement-acknowledgments"><h2>Customer Acknowledgments</h2><p>By signing, Customer confirms that Customer read the entire generated agreement; understands and voluntarily agrees to Sections 10 and 11; understands the excluded nonwaivable conduct; accepts responsibility for site, supervision, users, safe use, security, weather monitoring, and return; will stop use for unsafe equipment or conditions; consents to electronic records and signature; is at least 18 and authorized to sign; understands Regal Rentals selects the payment-security method; and reviewed these booking-specific equipment sections:</p><ul>${modules.map((id) => `<li>${esc(moduleTitles[id])}</li>`).join('')}</ul></section>`;
}

export function buildModularAgreementHtml(booking, input = {}) {
  const items = booking.items || [];
  const modules = determineAgreementModules(items);
  const paymentMethod = ['card_on_file', 'security_deposit'].includes(input.paymentSecurityMethod) ? input.paymentSecurityMethod : 'to_be_designated';
  const depositCents = input.securityDepositCents == null ? null : Number(input.securityDepositCents);
  return `<article class="agreement" data-agreement-version="${AGREEMENT_VERSION}" data-agreement-modules="${esc(modules.join(','))}"><header class="agreement-title"><p class="agreement-brand">UMBRYL LLC dba REGAL RENTALS</p><h1>Rental Agreement, Release of Liability, Assumption of Risk, and Indemnity</h1><p>Customer Use Version ${AGREEMENT_VERSION} · Effective ${EFFECTIVE_DATE}</p></header><div class="agreement-warning"><strong>This Agreement affects legal rights.</strong> Read it before signing. No equipment will be released until the Agreement is accepted and the payment-security method designated by Regal Rentals is completed.</div>${summary(booking, items, paymentMethod, depositCents)}${core(booking, modules, paymentMethod)}${addenda(modules)}${scheduleAndAcknowledgments(modules)}<footer class="agreement-footer"><strong>UMBRYL LLC dba REGAL RENTALS</strong><span>Version ${AGREEMENT_VERSION} · Generated specifically for ${esc(booking.booking_number)}</span></footer></article>`.trim();
}

async function loadBooking(db, bookingId) {
  const booking = await db.prepare(`SELECT b.*, c.name AS customer_name, c.email AS customer_email, c.phone AS customer_phone FROM bookings b JOIN customers c ON c.id = b.customer_id WHERE b.id = ?1`).bind(bookingId).first();
  if (!booking) return null;
  const result = await db.prepare(`SELECT bi.product_id, bi.quantity, bi.unit_price_cents, p.name, p.sku, p.category, p.style, p.description FROM booking_items bi JOIN products p ON p.id = bi.product_id WHERE bi.booking_id = ?1 ORDER BY p.category, p.sort_order, p.name`).bind(bookingId).all();
  booking.items = result.results || [];
  return booking;
}

export async function createModularSigningRequest(env, bookingId, user, input = {}) {
  const booking = await loadBooking(env.DB, bookingId);
  if (!booking) throw new Error('BOOKING_NOT_FOUND');
  const latest = await env.DB.prepare('SELECT COALESCE(MAX(agreement_version), 0) AS version FROM signing_requests WHERE booking_id = ?1').bind(booking.id).first();
  const version = Number(latest?.version || 0) + 1;
  const signerName = cleanText(input.signerName || booking.customer_name, 150);
  const signerEmail = normalizeEmail(input.signerEmail || booking.customer_email);
  if (!signerName || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(signerEmail)) throw new Error('INVALID_SIGNER');
  const paymentSecurityMethod = ['card_on_file', 'security_deposit'].includes(input.paymentSecurityMethod) ? input.paymentSecurityMethod : 'to_be_designated';
  const securityDepositCents = input.securityDepositCents == null ? null : Math.max(0, Math.round(Number(input.securityDepositCents)));
  const agreementHtml = buildModularAgreementHtml(booking, { paymentSecurityMethod, securityDepositCents });
  const agreementSha256 = await sha256(agreementHtml);
  const rawToken = crypto.getRandomValues(new Uint8Array(32));
  const token = Array.from(rawToken, (byte) => byte.toString(16).padStart(2, '0')).join('');
  const tokenHash = await sha256(token);
  const now = Math.floor(Date.now() / 1000);
  const expiresAt = now + Math.min(60 * 60 * 24 * 30, Math.max(60 * 60, Number(input.expiresInSeconds || 60 * 60 * 24 * 7)));
  await env.DB.prepare(`INSERT INTO signing_requests (token_hash, booking_id, signer_name, signer_email, agreement_version, agreement_html, agreement_sha256, expires_at, created_by, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)`).bind(tokenHash, booking.id, signerName, signerEmail, version, agreementHtml, agreementSha256, expiresAt, user.id, now).run();
  return { token, expiresAt, version, modules: determineAgreementModules(booking.items), paymentSecurityMethod, signingUrl: `${input.origin || ''}/sign.html?token=${encodeURIComponent(token)}` };
}
